# Generated by Django 3.0.5 on 2020-05-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_demo', '0002_new_relation_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_achievement_tab',
            name='create_time',
        ),
    ]
