# Generated by Django 3.0.5 on 2020-05-07 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dm_demo', '0003_remove_new_achievement_tab_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_achievement_tab',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
